// ============================================
// 🔧 Configuration - TEMPLATE
// ============================================
// DO NOT EDIT THIS FILE WITH REAL KEYS.
// Create a file named 'config.js' and copy this content there.

const CONFIG_SETTINGS = {
    // ===========================================
    // 🔴 AZURE OPENAI
    // ===========================================
    AZURE_OPENAI_ENDPOINT: "YOUR_AZURE_ENDPOINT_HERE",
    AZURE_OPENAI_API_KEY: "YOUR_AZURE_KEY_HERE",
    AZURE_OPENAI_DEPLOYMENT: "gpt-4o",
    AZURE_OPENAI_API_VERSION: "2024-08-01-preview",
    
    // ===========================================
    // 🟢 TENOR API
    // ===========================================
    TENOR_API_KEY: "AIzaSyAyimkuYQYF_FXVALexPuGQctUWRURdCYQ", // Public demo key
    
    // ===========================================
    // ⚙️ APP SETTINGS
    // ===========================================
    VLM_ANALYSIS_INTERVAL: 4000,
    FACE_DETECTION_INTERVAL: 150,
    MIN_FACE_CONFIDENCE: 0.5,
    ENABLE_VLM: true,
    ENABLE_MEME_SEARCH: true,
};

window.APP_CONFIG = CONFIG_SETTINGS;
