// ============================================
// 🔧 Configuration - TEMPLATE
// ============================================
// DO NOT EDIT THIS FILE WITH REAL KEYS.
// Create a file named 'config.js' and copy this content there.
// For Vercel deployment, set these as Environment Variables.

const CONFIG_SETTINGS = {
    // ===========================================
    // 🔴 AZURE OPENAI (Required for AI features)
    // ===========================================
    AZURE_OPENAI_ENDPOINT: "YOUR_AZURE_ENDPOINT_HERE",
    AZURE_OPENAI_API_KEY: "YOUR_AZURE_KEY_HERE",
    AZURE_OPENAI_DEPLOYMENT: "gpt-4o",
    AZURE_OPENAI_API_VERSION: "2025-01-01-preview",
    
    // ===========================================
    // 🟢 TENOR API (Has default - works out of box)
    // ===========================================
    TENOR_API_KEY: "AIzaSyAyimkuYQYF_FXVALexPuGQctUWRURdCYQ", // Public demo key
    
    // ===========================================
    // ⚙️ FEATURE TOGGLES
    // ===========================================
    ENABLE_VLM: true,          // Enable Azure OpenAI for AI captions
    ENABLE_MEME_SEARCH: true,  // Enable Tenor GIF search
};

window.APP_CONFIG = CONFIG_SETTINGS;
